services:
  db:
    image: postgres
    container_name: gestion_biblioteca
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gestion_biblioteca
    env_file:
      - "dev.env"
