# Generated by Django 5.1 on 2024-08-31 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.authors')),
                ('genre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genre.gender')),
            ],
        ),
    ]
