# Generated by Django 5.1 on 2024-08-31 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('statu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statu.status'),
        ),
    ]
